Fix PermissionsDropdown.tsx style error
The error `src/components/developer/PermissionsDropdown.tsx(126,14): error TS2322: Type '{ children: string; jsx: true; global: true; }' is not assignable to type 'DetailedHTMLProps<StyleHTMLAttributes<HTMLStyleElement>, HTMLStyleElement>'. Property 'jsx' does not exist on type 'DetailedHTMLProps<StyleHTMLAttributes<HTMLStyleElement>, HTMLStyleElement>'` indicates an issue with how the `style jsx global` is being used. This commit will address the type mismatch.